### ISSUE TITLE
Maybe use a different name?

### ISSUE THREAD

**Issue by mnunberg** [tombentley/jsonsl#10]
I'm the author of jsonsl (https://github.com/mnunberg/jsonsl), a minimal high performance C library that I've been maintaining for almost four years.

I see you've decided to name your project jsonsl. To avoid confusion, maybe select a different name if your Ceylon module ever becomes popular?

**Comment by tombentley** [comment]
Don't worry, this module was experimental and the way Ceylon does serialization has moved on, so I can _guarantee_ this will never become popular. At some point I will delete this repo (but not quite yet).
